// IPC channel constants — shared between main and renderer

export const IPC = {
  REPO: {
    OPEN: "git:repo:open",
    OPEN_DIALOG: "git:repo:open-dialog",
    CLOSE: "git:repo:close",
    INIT: "git:repo:init",
    GET_RECENT: "git:repo:get-recent",
    REMOVE_RECENT: "git:repo:remove-recent",
    CLEAR_RECENT: "git:repo:clear-recent",
    REMOVE_MISSING: "git:repo:remove-missing",
    GET_INFO: "git:repo:get-info",
    SET_CATEGORY: "git:repo:set-category",
    GET_CATEGORIES: "git:repo:get-categories",
    RENAME_CATEGORY: "git:repo:rename-category",
    DELETE_CATEGORY: "git:repo:delete-category",
    BROWSE_DIRECTORY: "git:repo:browse-directory",
    SCAN_FOR_REPOS: "git:repo:scan-for-repos",
    OPEN_EXTERNAL: "git:repo:open-external",
    GET_LAST_OPENED: "git:repo:get-last-opened",
    GET_VIEW_SETTINGS: "git:repo:get-view-settings",
    SET_VIEW_SETTINGS: "git:repo:set-view-settings",
  },
  STATUS: {
    GET: "git:status:get",
    STAGE: "git:status:stage",
    STAGE_LINES: "git:status:stage-lines",
    UNSTAGE: "git:status:unstage",
    UNSTAGE_LINES: "git:status:unstage-lines",
    DISCARD: "git:status:discard",
    DISCARD_ALL: "git:status:discard-all",
  },
  COMMIT: {
    CREATE: "git:commit:create",
    AMEND: "git:commit:amend",
    GET_RECENT_MESSAGES: "git:commit:get-recent-messages",
  },
  LOG: {
    GRAPH: "git:log:graph",
    DETAILS: "git:log:details",
    FULL_INFO: "git:log:full-info",
  },
  BRANCH: {
    LIST: "git:branch:list",
    CREATE: "git:branch:create",
    DELETE: "git:branch:delete",
    DELETE_REMOTE: "git:branch:delete-remote",
    RENAME: "git:branch:rename",
    CHECKOUT: "git:branch:checkout",
    MERGE: "git:branch:merge",
    REBASE: "git:branch:rebase",
    REBASE_INTERACTIVE: "git:branch:rebase-interactive",
    REBASE_COMMITS: "git:branch:rebase-commits",
    REBASE_CONTINUE: "git:branch:rebase-continue",
    REBASE_ABORT: "git:branch:rebase-abort",
    REBASE_IN_PROGRESS: "git:branch:rebase-in-progress",
    CHERRY_PICK: "git:branch:cherry-pick",
    RESET: "git:branch:reset",
  },
  TAG: {
    LIST: "git:tag:list",
    CREATE: "git:tag:create",
    DELETE: "git:tag:delete",
    PUSH: "git:tag:push",
  },
  REMOTE: {
    LIST: "git:remote:list",
    ADD: "git:remote:add",
    REMOVE: "git:remote:remove",
    PUSH: "git:remote:push",
    PULL: "git:remote:pull",
    PULL_REBASE: "git:remote:pull-rebase",
    PULL_MERGE: "git:remote:pull-merge",
    FETCH: "git:remote:fetch",
    FETCH_ALL: "git:remote:fetch-all",
    FETCH_PRUNE: "git:remote:fetch-prune",
    CLONE: "git:remote:clone",
    LIST_REMOTE_BRANCHES: "git:remote:list-remote-branches",
  },
  DIFF: {
    FILE: "git:diff:file",
    COMMIT: "git:diff:commit",
    COMMIT_FILE: "git:diff:commit-file",
    COMMIT_FILES: "git:diff:commit-files",
    STAGED: "git:diff:staged",
  },
  STASH: {
    LIST: "git:stash:list",
    CREATE: "git:stash:create",
    POP: "git:stash:pop",
    APPLY: "git:stash:apply",
    DROP: "git:stash:drop",
  },
  BLAME: {
    FILE: "git:blame:file",
  },
  HISTORY: {
    FILE: "git:history:file",
  },
  SUBMODULE: {
    LIST: "git:submodule:list",
    ADD: "git:submodule:add",
    UPDATE: "git:submodule:update",
  },
  SETTINGS: {
    GET: "git:settings:get",
    UPDATE: "git:settings:update",
    GET_AUTO_FETCH: "git:settings:get-auto-fetch",
    SET_AUTO_FETCH: "git:settings:set-auto-fetch",
  },
  GIT_CONFIG: {
    GET: "git:config:get",
    SET: "git:config:set",
    LIST: "git:config:list",
  },
  GITIGNORE: {
    ADD: "git:gitignore:add",
  },
  SHELL: {
    OPEN_FILE: "shell:open-file",
    SHOW_IN_FOLDER: "shell:show-in-folder",
    OPEN_FILE_IN_EDITOR: "shell:open-file-in-editor",
  },
  // Events pushed from main → renderer
  EVENTS: {
    COMMAND_LOG: "git:event:command-log",
    REPO_CHANGED: "git:event:repo-changed",
    SCAN_PROGRESS: "git:event:scan-progress",
  },
} as const;
