// IPC channel constants — shared between main and renderer

export const IPC = {
  REPO: {
    OPEN: "git:repo:open",
    OPEN_DIALOG: "git:repo:open-dialog",
    CLOSE: "git:repo:close",
    INIT: "git:repo:init",
    GET_RECENT: "git:repo:get-recent",
    REMOVE_RECENT: "git:repo:remove-recent",
    CLEAR_RECENT: "git:repo:clear-recent",
    REMOVE_MISSING: "git:repo:remove-missing",
    GET_INFO: "git:repo:get-info",
    SET_CATEGORY: "git:repo:set-category",
    GET_CATEGORIES: "git:repo:get-categories",
    RENAME_CATEGORY: "git:repo:rename-category",
    DELETE_CATEGORY: "git:repo:delete-category",
    BROWSE_DIRECTORY: "git:repo:browse-directory",
    BROWSE_FILE: "git:repo:browse-file",
    SCAN_FOR_REPOS: "git:repo:scan-for-repos",
    OPEN_EXTERNAL: "git:repo:open-external",
    GET_LAST_OPENED: "git:repo:get-last-opened",
    GET_VIEW_SETTINGS: "git:repo:get-view-settings",
    SET_VIEW_SETTINGS: "git:repo:set-view-settings",
  },
  STATUS: {
    GET: "git:status:get",
    STAGE: "git:status:stage",
    STAGE_LINES: "git:status:stage-lines",
    UNSTAGE: "git:status:unstage",
    UNSTAGE_LINES: "git:status:unstage-lines",
    DISCARD: "git:status:discard",
    DISCARD_ALL: "git:status:discard-all",
  },
  COMMIT: {
    CREATE: "git:commit:create",
    AMEND: "git:commit:amend",
    GET_RECENT_MESSAGES: "git:commit:get-recent-messages",
  },
  LOG: {
    GRAPH: "git:log:graph",
    DETAILS: "git:log:details",
    FULL_INFO: "git:log:full-info",
    SHOW_FILE: "git:log:show-file",
    SEARCH: "git:log:search",
  },
  BRANCH: {
    LIST: "git:branch:list",
    CREATE: "git:branch:create",
    DELETE: "git:branch:delete",
    DELETE_REMOTE: "git:branch:delete-remote",
    RENAME: "git:branch:rename",
    CHECKOUT: "git:branch:checkout",
    CHECKOUT_OPTIONS: "git:branch:checkout-options",
    MERGE: "git:branch:merge",
    MERGE_OPTIONS: "git:branch:merge-options",
    REBASE: "git:branch:rebase",
    REBASE_OPTIONS: "git:branch:rebase-options",
    REBASE_INTERACTIVE: "git:branch:rebase-interactive",
    REBASE_COMMITS: "git:branch:rebase-commits",
    REBASE_CONTINUE: "git:branch:rebase-continue",
    REBASE_SKIP: "git:branch:rebase-skip",
    REBASE_ABORT: "git:branch:rebase-abort",
    REBASE_IN_PROGRESS: "git:branch:rebase-in-progress",
    CHERRY_PICK: "git:branch:cherry-pick",
    CHERRY_PICK_OPTIONS: "git:branch:cherry-pick-options",
    REVERT: "git:branch:revert",
    MERGE_ABORT: "git:branch:merge-abort",
    MERGE_CONTINUE: "git:branch:merge-continue",
    CHERRY_PICK_ABORT: "git:branch:cherry-pick-abort",
    CHERRY_PICK_CONTINUE: "git:branch:cherry-pick-continue",
    RESET: "git:branch:reset",
    SQUASH_PREVIEW: "git:branch:squash-preview",
    SQUASH_EXECUTE: "git:branch:squash-execute",
    STALE_REMOTE: "git:branch:stale-remote",
    REMOTE_COMMITS: "git:branch:remote-commits",
  },
  TAG: {
    LIST: "git:tag:list",
    CREATE: "git:tag:create",
    DELETE: "git:tag:delete",
    DELETE_REMOTE: "git:tag:delete-remote",
    PUSH: "git:tag:push",
  },
  REMOTE: {
    LIST: "git:remote:list",
    ADD: "git:remote:add",
    REMOVE: "git:remote:remove",
    PUSH: "git:remote:push",
    PULL: "git:remote:pull",
    PULL_REBASE: "git:remote:pull-rebase",
    PULL_MERGE: "git:remote:pull-merge",
    FETCH: "git:remote:fetch",
    FETCH_ALL: "git:remote:fetch-all",
    FETCH_PRUNE: "git:remote:fetch-prune",
    CLONE: "git:remote:clone",
    LIST_REMOTE_BRANCHES: "git:remote:list-remote-branches",
  },
  DIFF: {
    FILE: "git:diff:file",
    COMMIT: "git:diff:commit",
    COMMIT_FILE: "git:diff:commit-file",
    COMMIT_FILES: "git:diff:commit-files",
    STAGED: "git:diff:staged",
    RANGE_FILES: "git:diff:range-files",
    RANGE_FILE: "git:diff:range-file",
    TREE_FILES: "git:diff:tree-files",
  },
  STASH: {
    LIST: "git:stash:list",
    CREATE: "git:stash:create",
    POP: "git:stash:pop",
    APPLY: "git:stash:apply",
    DROP: "git:stash:drop",
  },
  BLAME: {
    FILE: "git:blame:file",
  },
  HISTORY: {
    FILE: "git:history:file",
  },
  SUBMODULE: {
    LIST: "git:submodule:list",
    ADD: "git:submodule:add",
    UPDATE: "git:submodule:update",
    SYNC: "git:submodule:sync",
    DEINIT: "git:submodule:deinit",
    STATUS: "git:submodule:status",
  },
  SETTINGS: {
    GET: "git:settings:get",
    UPDATE: "git:settings:update",
    GET_AUTO_FETCH: "git:settings:get-auto-fetch",
    SET_AUTO_FETCH: "git:settings:set-auto-fetch",
  },
  GIT_CONFIG: {
    GET: "git:config:get",
    SET: "git:config:set",
    LIST: "git:config:list",
  },
  CONFLICT: {
    LIST: "git:conflict:list",
    FILE_CONTENT: "git:conflict:file-content",
    RESOLVE: "git:conflict:resolve",
    SAVE_MERGED: "git:conflict:save-merged",
    LAUNCH_MERGE_TOOL: "git:conflict:launch-merge-tool",
  },
  OPERATION: {
    CANCEL: "git:operation:cancel",
  },
  GITIGNORE: {
    ADD: "git:gitignore:add",
    READ: "git:gitignore:read",
    WRITE: "git:gitignore:write",
    PREVIEW: "git:gitignore:preview",
    TEMPLATES: "git:gitignore:templates",
  },
  ACCOUNT: {
    LIST: "git:account:list",
    ADD: "git:account:add",
    UPDATE: "git:account:update",
    DELETE: "git:account:delete",
    GET_FOR_REPO: "git:account:get-for-repo",
    SET_FOR_REPO: "git:account:set-for-repo",
    GET_DEFAULT: "git:account:get-default",
    SET_DEFAULT: "git:account:set-default",
    PARSE_SSH_CONFIG: "git:account:parse-ssh-config",
  },
  TERMINAL: {
    SPAWN: "terminal:spawn",
    INPUT: "terminal:input",
    RESIZE: "terminal:resize",
    KILL: "terminal:kill",
  },
  SHELL: {
    OPEN_FILE: "shell:open-file",
    SHOW_IN_FOLDER: "shell:show-in-folder",
    OPEN_FILE_IN_EDITOR: "shell:open-file-in-editor",
  },
  MCP: {
    // Server management
    SERVER_START: "mcp:server:start",
    SERVER_STOP: "mcp:server:stop",
    SERVER_STATUS: "mcp:server:status",
    // AI operations
    GENERATE_COMMIT_MESSAGE: "mcp:ai:generate-commit-message",
    SUGGEST_CONFLICT_RESOLUTION: "mcp:ai:suggest-conflict-resolution",
    GENERATE_PR_DESCRIPTION: "mcp:ai:generate-pr-description",
    REVIEW_COMMIT: "mcp:ai:review-commit",
  },
  APP: {
    CHECK_FOR_UPDATES: "app:check-for-updates",
    GET_VERSION: "app:get-version",
    UPDATE_STATUS: "app:update-status",
    OPEN_USER_MANUAL: "app:open-user-manual",
  },
  MENU: {
    OPEN_REPO: "menu:open-repo",
  },
  // Events pushed from main → renderer
  EVENTS: {
    COMMAND_LOG: "git:event:command-log",
    COMMAND_OUTPUT: "git:event:command-output",
    REPO_CHANGED: "git:event:repo-changed",
    SCAN_PROGRESS: "git:event:scan-progress",
    TERMINAL_DATA: "terminal:data",
    TERMINAL_EXIT: "terminal:exit",
  },
  DIALOG: {
    OPEN: "dialog:open",
    CLOSE: "dialog:close",
    GET_INIT_DATA: "dialog:get-init-data",
    RESULT: "dialog:result",
    ON_RESULT: "dialog:on-result",
  },
  STATS: {
    LEADERBOARD: "git:stats:leaderboard",
    AUTHOR_DETAIL: "git:stats:author-detail",
    CODEBASE: "git:stats:codebase",
  },
  REFLOG: {
    LIST: "git:reflog:list",
  },
  ARCHIVE: {
    EXPORT: "git:archive:export",
  },
  BISECT: {
    START: "git:bisect:start",
    GOOD: "git:bisect:good",
    BAD: "git:bisect:bad",
    SKIP: "git:bisect:skip",
    RESET: "git:bisect:reset",
    LOG: "git:bisect:log",
    STATUS: "git:bisect:status",
  },
  WORKTREE: {
    LIST: "git:worktree:list",
    ADD: "git:worktree:add",
    REMOVE: "git:worktree:remove",
  },
  PATCH: {
    CREATE: "git:patch:create",
    APPLY: "git:patch:apply",
    PREVIEW: "git:patch:preview",
  },
  NOTES: {
    GET: "git:notes:get",
    ADD: "git:notes:add",
    REMOVE: "git:notes:remove",
  },
  GPG: {
    VERIFY: "git:gpg:verify",
  },
  LFS: {
    STATUS: "git:lfs:status",
    LIST_TRACKED: "git:lfs:list-tracked",
    TRACK: "git:lfs:track",
    UNTRACK: "git:lfs:untrack",
    INFO: "git:lfs:info",
    INSTALL: "git:lfs:install",
  },
  PR: {
    LIST: "git:pr:list",
    VIEW: "git:pr:view",
    CREATE: "git:pr:create",
    DETECT_PROVIDER: "git:pr:detect-provider",
  },
  CHANGELOG: {
    TAGS_BEFORE: "git:changelog:tags-before",
    GENERATE: "git:changelog:generate",
  },
  GREP: {
    SEARCH: "git:grep:search",
  },
  DIFF_BRANCHES: {
    COMPARE: "git:diff:branches",
  },
  LOG_RANGE: {
    COMPARE: "git:log:range",
  },
  UNDO: {
    HISTORY: "git:undo:history",
    REVERT: "git:undo:revert",
  },
  HOOKS: {
    LIST: "git:hooks:list",
    READ: "git:hooks:read",
    WRITE: "git:hooks:write",
    TOGGLE: "git:hooks:toggle",
    DELETE: "git:hooks:delete",
  },
  CI: {
    STATUS: "ci:status:get",
  },
  ISSUES: {
    RESOLVE: "issues:resolve",
  },
  GIST: {
    CREATE: "gist:create",
  },
  STATS_ADVANCED: {
    TIMELINE: "git:stats:timeline",
    CHURN: "git:stats:churn",
    CONTRIBUTORS_TIMELINE: "git:stats:contributors-timeline",
  },
  REVIEW: {
    SAVE: "review:comments:save",
    LOAD: "review:comments:load",
    CLEAR: "review:comments:clear",
    LIST_REVIEWS: "review:comments:list",
  },
  SSH: {
    LIST: "ssh:keys:list",
    GENERATE: "ssh:keys:generate",
    GET_PUBLIC: "ssh:keys:get-public",
    TEST: "ssh:keys:test",
  },
} as const;
